add cancelAnimationFrame for useRafFn
vueuse/vueuse pull request #1502
Opened 2022-04-18 12:07 UTC by r1ader

### Description

This commit is out of my notice about the green button `Transition` in [useTransition demo](https://vueuse.org/core/usetransition/) 

If you use the performance panel of chrome dev tool to record , and then click button `Transition` quickily for several times.

And then you will find there are many `Animation Frame Fired` in just one frame.

This commit try to add `cancelAnimationFrame` to avoid the unnecessary invoke of the repeated raf callbacks

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-04-18 12:19 UTC, okxiaoliang4 requested changes

2022-04-18 12:19 UTC, okxiaoliang4 commented on packages/core/useRafFn/index.ts
> +    if(rafId.value && window){
```suggestion
    if(rafId.value && window) {
```

2022-04-18 12:29 UTC, okxiaoliang4 submitted a review, later dismissed

2022-04-18 15:28 UTC, antfu commented on packages/core/useRafFn/index.ts
> +  const rafId = ref(null) as Ref<null | number>
```suggestion
  const rafId: number | undefined
```

This does not need to be a ref

2022-04-19 03:31 UTC, antfu commented on packages/core/useRafFn/index.ts
> +    if (typeof rafId === 'number' && window) {
```suggestion
    if (rafId != null && window) {
```

2022-04-19 03:32 UTC, merged