feat(useTrunk): new function
vueuse/vueuse pull request #1838
Opened 2022-07-10 08:58 UTC by hanpei

### Description

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-10 09:11 UTC, antfu commented on packages/math/useTrunc/index.test.ts
> +// 返回：
```suggestion
// Returns:
```

2022-07-10 09:12 UTC, antfu requested changes

2022-07-10 09:12 UTC, antfu commented on packages/math/useTrunc/index.ts
> +export function useTrunk(value: MaybeComputedRef<number>): ComputedRef<number> {
```suggestion
export function useTrunc(value: MaybeComputedRef<number>): ComputedRef<number> {
```

2022-07-10 09:12 UTC, antfu commented on packages/math/useTrunc/index.ts
> +      return Math.ceil(resolveUnref(value))
Why don't we use `Math.trunc` directly?

2022-07-13 07:07 UTC, hanpei commented
i've push the changes, what should i do next?

2022-07-17 07:38 UTC, antfu approved these changes

2022-07-17 07:38 UTC, merged