feat(useOnce): new function
vueuse/vueuse pull request #2046
Opened 2022-08-05 01:37 UTC by icooooler

### Description

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-30 06:58 UTC, songjianet approved these changes
LGTM

2022-09-04 08:45 UTC, sxzz requested changes

2022-09-04 08:45 UTC, sxzz commented on packages/core/useOnce/index.ts
> +  const action = () => {
I think it should be a verb. How about `execute`?

2022-09-04 08:45 UTC, sxzz commented on packages/core/useOnce/index.ts
> +  // 执行
We should use English in an international project.

2022-09-04 08:45 UTC, sxzz commented on packages/core/useOnce/index.ts
> +  const canUse = ref(true)
`executed`

2022-09-04 08:45 UTC, sxzz commented on packages/core/useOnce/index.md
> +make a function can only be used once.
```suggestion
A function that can only be executed once.
```

2022-09-05 13:59 UTC, antfu commented
Thanks but I don't think this is related to VueUse - you can achieve this without using Vue's reactivity. This is considered as out-of-scope.

2022-09-05 13:59 UTC, closed without merging