feat(useContextMenu): new function
vueuse/vueuse pull request #2151
Opened 2022-08-31 11:32 UTC by vaakian

### Description

Add [`contextMenu(s)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) to the page with ease. 

https://user-images.githubusercontent.com/30516060/187668848-80200739-b3ce-4430-bc95-c930236816f7.mov

### Additional context

#### Includes 3 incremental changes:
* fix(useMouseInElement): use `MaybeComputedElementRef`
* feat(useElementSize): support  `box` sizing: [description](https://github.com/vueuse/vueuse/pull/2143)
* feat(useWindowSize): support `includeScrollbar` option: [description](https://github.com/vaakian/vueuse/pull/1)

I was struggled and failed on how to make [stacked PRs](https://blog.logrocket.com/using-stacked-pull-requests-in-github/), so I am sorry bring all there changes on this single pull request.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2022-09-01 01:34 UTC, songjianet requested changes
You don't have to close the previous pr. If it is closed, you need to review it again. Can you do some unit testing on this feature and fix the previous review. https://github.com/vueuse/vueuse/pull/2136

2022-09-01 08:39 UTC, vaakian commented
> You don't have to close the previous pr. If it is closed, you need to review it again. Can you do some unit testing on this feature and fix the previous review. #2136

A unit testing file is included in the latest commit. but t's quite verbose in some way(:

2022-09-01 14:20 UTC, vaakian commented on packages/core/useContextMenu/index.md
> +    <Area wa>
Oh, sure! I didn't notice it when pasting that piece of code from demo.

2022-09-01 14:31 UTC, vaakian commented
> I think any changes to other composables(e.g. useMouseInElement) should be done in separate PRs

I thought the same, but this PR needs those changes to make the new function work, so I must wait until those separate PRs are merged before opening this PR, otherwise the CI would fail.

Sorry about my terrible git skill, is there a decent work around to do this?

2022-09-01 14:34 UTC, wheatjs commented
It would be best to open up the other PRs and just make a note of it in this one that it depends on the other PRs. Once those are merged you can then bring this on up to date with main and then the tests will pass

2022-09-07 10:17 UTC, vaakian commented on packages/core/useContextMenu/index.ts
> +    useEventListener('blur', hide),
💡 Got an idea about `useEventListener`
```ts
// multi event
useEventListener(['scroll', 'click', 'resize', 'blur'], handler)

// multi handler
useEventListener('scroll' [handler1, handler2, handler3])

// multi event & multi handler
useEventListener(['scroll', 'click', 'resize', 'blur'], [handler1, handler2, handler3])
```

2022-09-07 10:27 UTC, vaakian commented on packages/core/useContextMenu/index.ts
> +    useEventListener('blur', hide),
seems not to be the right place, I will place this idea somewhere else later on.😂

2022-12-18 14:18 UTC, vaakian commented
Oh! how did I just accidentially closed this PR, sorry for the disturbance.

2023-06-20 10:56 UTC, closed without merging