fix: ElementBounding Scroll #2319
vueuse/vueuse pull request #2596
Opened 2022-12-29 16:28 UTC by Ducz01

### Description

Closes #2319, The Scrolling of useElementBounding didn't work when a div gets scrolled, only when the window was scrolled. Now it works.

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-12-29 17:48 UTC, sibbng requested changes

2022-12-29 17:48 UTC, sibbng commented on packages/core/useElementBounding/index.ts
> +    useEventListener('scroll', update, true, { passive: true })
```suggestion
    useEventListener('scroll', update, { capture: true, passive: true })
```

2022-12-30 14:23 UTC, dpschen approved these changes

2022-12-30 17:55 UTC, sibbng approved these changes

2022-12-30 17:55 UTC, merged