feat(createGlobalState): allow passing initial config
vueuse/vueuse pull request #2790
Opened 2023-02-19 13:01 UTC by jd-solanki

### Description

[`createGlobalState`](https://vueuse.org/shared/createGlobalState/) is nice and I wanted to use it for configuring [Anu](https://anu-vue.netlify.app/) instance when vue uses it as a plugin. However, `createGlobalState` doesn't accepts any initial config for initializing global state based on provided config.

### Additional context

This is really simple change but don't forget to review it 👀 

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-02-19 14:24 UTC, jd-solanki commented
Still, I'm not satisfied with the API it provides. I can initialize the composable with options and don't want to require them later. However, when we use it, every time it gives `...args: any[]` as a type of argument for composable.

Moreover, We can include a generic type of accepting the type of params we can pass to avoid errors while defining options:
```ts
// Nothing, I can pass anything I want as options
useAnu({
  initialTheme: config.initialTheme,
  themes: config.themes,
})

// We can add nice autocompletion and add restrictions for error detection
useAnu<AnuOptions>({
  initialTheme: config.initialTheme,
  themes: config.themes,
})
```

Feel free to update the PR 😇

2023-02-20 11:16 UTC, antfu requested changes
In general it's ok, but can we make it type-safe? Thanks

2023-02-20 11:39 UTC, jd-solanki commented
Unfortunately, I'm not good enough with typescript to improve this, I'm still improving my TS game. I referenced [createSharedComposable](https://github.com/vueuse/vueuse/blob/main/packages/shared/createSharedComposable/index.ts).

I hope you will understand, Thanks.

2023-03-02 11:58 UTC, antfu approved these changes

2023-03-04 12:56 UTC, merged