feat(useElementOverflow): new function
vueuse/vueuse pull request #4094
Opened 2024-07-11 05:20 UTC by inside5545

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

this function helps to react a dom's overflow state, the scenario is that sometimes we need to determine if a container dom become overlength and then need to add some style. for example, maybe the text is too long, we need to add a tooltip bubble to it.

### Additional context

I already see the [Warning: Slowing down new functions],and I often create common components and codes, I think useElementOverflow is really necessary,so I take some time to create the hook,directive and components.

2024-07-23 01:37 UTC, inside5545 commented on packages/core/useElementOverflow/index.ts
> +export function useElementOverflow(target: MaybeComputedElementRef, option: UseElementOverflowOptions = {}) {
@zyyv Thanks,I added some for it.

2024-12-30 16:05 UTC, OrbisK commented
Hey @inside5545 thanks for your PR,

In order to eventually merge this, we need to cover this with tests so that it is easier to maintain. Could you imagine writing the tests for this, or do you need any support? Please let me know :)

2025-01-02 01:13 UTC, inside5545 commented
@OrbisK Thank you for your reply, of course, but I have a lot of work at the end of the year, so I may do it slowly. I would appreciate it if someone could help me finish it. Or if you're sure it's going to be merged, I'll try harder to find the time to add the tests

2025-01-03 12:33 UTC, OrbisK commented
this should also fix #3686

2025-01-03 12:44 UTC, inside5545 commented
@OrbisK I'll try to find the time to do it, but I still want someone to help me finish it. TAT~

2025-01-03 12:58 UTC, inside5545 commented
@OrbisK I added tests today,but CI workflow seems to have a few problem,I haven't had a chance to check.The second thing is that #3686 you just mentioned,it still needs some time.I'm not quite sure when I'll have time to deal with it. There's too much to do at Chinese New Year. TAT~

2025-01-03 13:04 UTC, OrbisK commented
> @OrbisK I added tests today,but CI workflow seems to have a few problem,I haven't had a chance to check.The second thing is that #3686 you just mentioned,it still needs some time.I'm not quite sure when I'll have time to deal with it. There's too much to do at Chinese New Year. TAT~

I will check the CI. 

I think if this will be merged. https://github.com/vueuse/vueuse/issues/3686 is also completed :) no actions to do there

2025-01-03 13:13 UTC, inside5545 commented
> > @OrbisK I added tests today,but CI workflow seems to have a few problem,I haven't had a chance to check.The second thing is that #3686 you just mentioned,it still needs some time.I'm not quite sure when I'll have time to deal with it. There's too much to do at Chinese New Year. TAT~
> 
> I will check the CI.
> 
> I think if this will be merged. #3686 is also completed :) no actions to do there

THANK YOU so so so much ~！

2025-01-23 09:25 UTC, inside5545 commented
@OrbisK I've updated the code, please merge the PR if it is convenient

2025-05-19 10:00 UTC, 43081j approved these changes, later dismissed
looks good to me 👍

2025-10-29 13:52 UTC, mrleblanc101 commented
Any update ?

2025-10-30 09:13 UTC, inside5545 commented
@OrbisK Could you please help handle the CI problem.This doesn't seem to be problems with my code

2025-10-30 09:37 UTC, OrbisK commented
@43081j can you check the attw errors?

2025-10-30 10:15 UTC, 43081j commented
they pass locally, but we should look into it

im traveling most of today so may not get chance. i would try run them locally under node 20 and see if you get the same error

2025-10-30 15:13 UTC, 9romise commented on packages/core/useElementOverflow/index.md
> +<script>
I think we could use the `<script setup>`.

2025-10-30 15:13 UTC, 9romise commented on packages/core/useElementOverflow/index.ts
> +        (onUpdated as ResizeObserverCallback)?.(entries, observer)
It feels slightly odd to me that both observers are calling the same `onUpdate` option. Is there any particular reason for this design?

2025-10-31 06:16 UTC, inside5545 commented on packages/core/useElementOverflow/index.ts
> +        (onUpdated as ResizeObserverCallback)?.(entries, observer)
Here’s how I think about it: in most cases, we only care whether the DOM element is overflowed or not, and don’t really need to know the exact cause of the overflow.  So sharing a single onUpdate callback makes it simpler to use.
If there’s indeed a need to distinguish between different triggers, we could either split it into two separate events or add a parameter to onUpdate to indicate the source.

2025-10-31 06:23 UTC, inside5545 commented on packages/core/useElementOverflow/index.md
> +<script>
ok,I used <script setup> instead.

2026-05-05 07:01 UTC, OrbisK submitted a review, later dismissed
would you mind solving the conflicts?

2026-05-07 06:33 UTC, inside5545 commented
> would you mind solving the conflicts?

I checked the Netlify deploy log, although I’m not very familiar with Netlify itself.

It looks like google-font-installer@1.2.0 may not be compatible with Node 24, but I’m not sure how Netlify is configured for this project.
Since the failure happens before docs:build starts, it seems unrelated to the useElementOverflow changes. Could a maintainer please help check whether the Netlify deploy preview should use a lower Node version, or whether the font installer step needs to be updated?

Latest failed deploy:
https://app.netlify.com/projects/vueuse/deploys/69fc2c9caa930b0008b92e06
Relevant log:
```txt
$ pnpm run install-fonts && pnpm run docs:build
> gfi install Inter && gfi install Fira Code

TypeError: util.isString is not a function
...
Node.js v24.15.0

2026-05-07 07:17 UTC, 9romise commented
> It looks like google-font-installer@1.2.0 may not be compatible with Node 24, but I’m not sure how Netlify is configured for this project. Since the failure happens before docs:build starts, it seems unrelated to the useElementOverflow changes. Could a maintainer please help check whether the Netlify deploy preview should use a lower Node version, or whether the font installer step needs to be updated?

This issue should have been fixed previously. Merging the latest branch should resolve it.

2026-05-08 06:27 UTC, inside5545 commented
> > It looks like google-font-installer@1.2.0 may not be compatible with Node 24, but I’m not sure how Netlify is configured for this project. Since the failure happens before docs:build starts, it seems unrelated to the useElementOverflow changes. Could a maintainer please help check whether the Netlify deploy preview should use a lower Node version, or whether the font installer step needs to be updated?
> 
> This issue should have been fixed previously. Merging the latest branch should resolve it.

Thanks, I checked again. My PR branch already includes the latest upstream `main`, including the `google-font-installer` patch from #5137.The failing log still shows `util.isString is not a function`.

It looks like the Netlify deploy preview may still be using a stale cached `node_modules` / dependency install where the patch was not applied. this PR has been open for quite a while.

Could a maintainer please retry the Netlify deploy with cache cleared?

2026-05-20 11:06 UTC, OrbisK requested changes

2026-05-20 11:06 UTC, OrbisK commented on packages/core/useElementOverflow/index.ts
> +    isYOverflowed,
lets expose those as `shallowReadonly`

2026-05-21 07:07 UTC, OrbisK commented on packages/core/useElementOverflow/index.ts
> +  tryOnUnmounted(stop)
I have to think about the disposal and effectscope here. I am not sure if we need the scope and if we should dispose it only on unmounted (vs `tryOnScopeDispose`).

What is the reason for the effectScope?

2026-05-21 07:19 UTC, 9romise commented on packages/core/useElementOverflow/directive.ts
We need to use `createDisposableDirective` to create a directive.

2026-05-22 06:07 UTC, inside5545 commented on packages/core/useElementOverflow/index.ts
> +  tryOnUnmounted(stop)
Thanks for the review.
On point 1 (effectScope): I originally used it out of habit and by following some other hooks in the library. And Revisiting it, I agree it isn't strictly necessary,creating those composables inside this local scope lets `useElementOverflow.stop()` clean them up explicitly, without relying only on the caller/component scope.If you prefer removing the `effectScope`, let me know and I'll remove it.
On point 2 (disposal): You're right, it should be tryOnScopeDispose. Already changed and pushed.

2026-05-22 06:08 UTC, inside5545 commented on packages/core/useElementOverflow/directive.ts
Thanks.Already changed and pushed.

2026-05-26 14:38 UTC, 43081j submitted a review, later dismissed

2026-05-26 15:02 UTC, OrbisK approved these changes

2026-05-26 15:49 UTC, OrbisK requested changes
I will make some changes tomorrow™️ . After that, I think it should be ready for a final review and merge.

2026-06-04 02:58 UTC, 9romise approved these changes

2026-06-04 08:37 UTC, OrbisK approved these changes

2026-06-04 16:11 UTC, ilyaliao approved these changes

2026-07-03 02:24 UTC, inside5545 commented
@OrbisK Is there a timeline for merging this PR?

2026-07-03 08:09 UTC, merged