feat(useCountdown): new function
vueuse/vueuse pull request #4125
Opened 2024-08-01 03:58 UTC by rtugeek

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Add a `useCountdown` function for simple number countdown scenarios. A classic use case: SMS verification code resend countdown.

- It's just a wrapper around `useIntervalFn`, and requestAnimationFrame is not used.
- `Controls` are not implemented for now, as most countdown scenarios require Controls.

### Additional context

https://github.com/vueuse/vueuse/pull/1035#issuecomment-994208498

2024-12-22 15:49 UTC, huang-julien requested changes

2024-12-22 15:49 UTC, huang-julien commented on packages/core/useCountdown/index.ts
> + * @param initialCountdown
We should specify that the countdown is in second to avoid confusing users since the interval is in ms

2024-12-22 15:49 UTC, huang-julien commented on packages/core/useCountdown/index.ts
> +    if (remaining.value === 0) {
```suggestion
    if (remaining.value <= 0) {
```

to avoid issues when having a 3.5s countdown

2025-01-02 05:20 UTC, reslear commented
any news?

2025-01-14 22:02 UTC, huang-julien approved these changes

2025-01-22 07:59 UTC, antfu approved these changes

2025-01-22 08:04 UTC, merged