feat(useStorageAsync): add onLoad option
vueuse/vueuse pull request #4158
Opened 2024-08-17 17:34 UTC by asika32764

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

This PR is aim to solve the issue https://github.com/vueuse/vueuse/issues/2895

Currently, `useStorageAsync` is impossible to listen to first value loaded, sometimes when app initializing, if we must use the storage, we may get the default initial value since the async storage not prepared.

This PR add an `onLoad` event to let developer can solve this problem by manually resolve promises in this callback.

### Additional context

2025-01-21 11:45 UTC, ferferga approved these changes
LGTM, but honestly, for the given use case, why not use the sync `useStorage`? I'm approving this though since other functions (like `useWebSocket`) supports similar callbacks as well.

2025-01-21 11:53 UTC, asika32764 commented
For example, the capacitorStorage is asynchronous.

And sometimes people may write their own storage adapter since useStorageAsync and useStorage allows custom storage interface as an argument.

2025-01-21 15:03 UTC, OrbisK requested changes

2025-01-21 15:03 UTC, OrbisK commented on packages/core/useStorageAsync/index.ts
> +  onLoad?: (value: T) => void
If `router` and others use `onReady`, we might also think about `onReady` to be consistent. In addition, `onReady` implies to be called once.

2025-01-21 15:03 UTC, OrbisK commented on packages/core/useStorageAsync/index.ts
> +    }
```suggestion
      onLoad?.(data.value)
```
I think this is a bit more consistent for example when someone accidentally passes a boolean. So `true` and `false` will both result in an error.

2025-01-22 14:02 UTC, OrbisK commented on packages/core/useStorageAsync/index.test.ts
> +  it('onLoad', () => {
```suggestion
  it('onReady', () => {
```

2025-01-23 06:30 UTC, OrbisK submitted a review, later dismissed

2025-01-23 07:04 UTC, OrbisK approved these changes

2025-02-12 02:29 UTC, antfu commented
I feel that exposing a `then` function to the ref might be more intuitive where users could also await for it.

It can be both:

```ts
const accessToken = await useStorageAsync('access.token', '', SomeAsyncStorage)
```

or 


```ts
const accessToken = useStorageAsync('access.token', '', SomeAsyncStorage)

accessToken.then(() => {
  // ...
})
```

2025-02-12 03:39 UTC, asika32764 commented
Maybe

```ts
accessToken.ready.then()
```

Some libraries use this way.

2025-03-19 06:21 UTC, asika32764 commented
So is there any update? Do we need to change to the new pattern?

2025-06-25 07:45 UTC, asika32764 commented
@antfu Sorry to bother but I think this function is required for peoples since there are some issues discussion about this feature.

If wee need more changes, please leave some messages so that I can modify the code.

Currently there has no any workaround to solve the async initialize issue without this PR.

2025-06-26 15:05 UTC, ilyaliao commented
> I feel that exposing a `then` function to the ref might be more intuitive where users could also await for it.
> 
> It can be both:
> 
> ```ts
> const accessToken = await useStorageAsync('access.token', '', SomeAsyncStorage)
> ```
> 
> or
> 
> ```ts
> const accessToken = useStorageAsync('access.token', '', SomeAsyncStorage)
> 
> accessToken.then(() => {
>   // ...
> })
> ```

It feels like using `useFetch`

```ts
const { isFetching, error, data } = await useFetch(url)
```

@asika32764  would you be open to exploring how we could support something like this?
Sorry for the late reply!

2025-06-27 12:00 UTC, asika32764 commented
I implemented the Promise to the return value. But I still keep `onReady` options if someone needs it.

```ts
const accessToken = useStorageAsync('access.token', '', SomeAsyncStorage, {
  onReady(value) {
    // ...
  }
})

accessToken.value // Origin way, may be empty if storage not prepared

const resolvedToken = await accessToken

resolvedToken.value // Resolved, still needs a .value to get value
```

2025-07-28 04:58 UTC, merged