fix(useStorageAsync): multi-tab deadlock
vueuse/vueuse pull request #4353
Opened 2024-11-22 00:10 UTC by afute

fix #4200 

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

When "useStorageAsync" is used, when more than one tab is opened, the value of the two tabs changes to each other, causing a deadlock

[bug video](https://github.com/afute/useStorageAsync-bug-example-p1/blob/main/example.mp4)

### Reproduction

https://github.com/afute/useStorageAsync-bug-example-p1

2024-12-22 05:33 UTC, antfu commented
Could you help to add some tests to prevent future regressions? Thanks

2025-01-31 16:02 UTC, Tofandel commented on packages/core/useStorageAsync/queue.ts
> +    this.queue[1] = task
Yikes!

Basically we just want to pause the watcher while the async read method is running, we have composables for that which could be used instead of this very shaky TaskQueue

2025-01-31 16:03 UTC, Tofandel commented on packages/core/useStorageAsync/queue.ts
> +    this.queue[1] = task
Yikes!

Basically we just want to pause the watcher while the async read method is running, we have composables for that which could be used instead of this very shaky TaskQueue

2025-01-31 16:10 UTC, Tofandel requested changes

2025-01-31 16:10 UTC, Tofandel commented on packages/core/useStorageAsync/index.ts
> +    })
From what I gathered this could just be simplified like this
```suggestion
    useEventListener(window, 'storage', async (e) => {
      watchStop()
      await read(e)
      watchStop = watchWithFilter(data, cb, {
        flush,
        deep,
        eventFilter,
      })
    })
```

2025-02-03 12:45 UTC, closed without merging

2025-02-03 13:52 UTC, afute commented on packages/core/useStorageAsync/index.ts
> +    })
Sorry to reply to you now, you are correct, I was trying to reduce the side effects of "setItem" at the time.

2025-02-03 15:24 UTC, Tofandel commented on packages/core/README.md
> +../../README.md
That's a weird changeset, what happened here?