feat(watchWithCount): new Function
vueuse/vueuse pull request #764
Opened 2021-09-16 11:21 UTC by webfansplz

see #762

2021-09-16 12:17 UTC, antfu commented
Looks interesting, but can you share a bit context of why this is useful?

2021-09-16 12:41 UTC, webfansplz commented
My initial idea was watchOnce (I use it a lot in my projects，but with watch i need to manually call the stop function). i use watchWithCount instead of watchOnce that because i think it's more flexible.

2021-09-16 12:47 UTC, patak-js commented
Maybe `watchN(4, ...)` or `watchAtMost(4, ...)` to be closer to `watchOnce`. A `watchUntil(ms,...)` may also be interesting 🤔

2021-09-16 12:48 UTC, patak-js commented
Do you have a concrete example where you used this @webfansplz? I'm also curious about your real use cases

2021-09-16 13:27 UTC, webfansplz commented
```ts

const { stop } = watch(
                props.response!,
                () => {
                    nextTick(() => {
                        const floor = route.query.floor
                        onToggleActiveFloor(Number(floor))
                        stop()
                    })
                },
                { immediate: true },
            )

```
This is one of the scenes: I need to listen for data responses and do UI initialization with route parameters.

2021-09-16 13:29 UTC, webfansplz commented
> Maybe `watchN(4, ...)` or `watchAtMost(4, ...)` to be closer to `watchOnce`. A `watchUntil(ms,...)` may also be interesting 🤔

i agree with you. maybe `watchAtMost(4, ...)` is more appropriate ~

2021-09-17 06:27 UTC, antfu requested changes
I think it would be great to also include a shorthand `watchOnce` that uses this function under the hood

2021-09-17 06:27 UTC, antfu commented on packages/shared/watchAtMost/index.ts
> +    createFilterWrapper(filter, (...args) => {
I don't think the filter is needed here (a bit overengineered from my point of view. Simply count and stop will be good enough.

2021-09-17 07:18 UTC, antfu commented
I will made the changes directly

2021-09-17 07:45 UTC, merged

2021-09-17 07:49 UTC, webfansplz commented
@antfu thanks~